### ISSUE TITLE
Missing mandatory keywords in FITS headers.

### ISSUE THREAD

**Issue by mkolopanis** [MWATelescope/Birli#9]
Thanks for the hard work getting MWAX up and running. This package is really nicely done.

I work on [pyuvdata](https://github.com/RadioAstronomySoftwareGroup/pyuvdata.gi) and I noticed some mandatory keywords from [AIPS 117](http://www.aips.nrao.edu/aipsmemo.html) are missing from birli UVFITS files. Our software is pretty flexible reading in different interferometric datasets but the "FRAME" keyword in particular in the "AIPS AN" table is important to know which frame the antenna positions are recorded in. I've made some [downstream issues](https://github.com/RadioAstronomySoftwareGroup/pyuvdata/issues/1085) to address this on read (assuming it is "ITRF" like previous MWA files), but though I would make you all aware as well.

**Comment by derwentx** [comment]
Thanks @mkolopanis , I really appreciate you letting us know about this, and big ups to you too for your work on pyuvdata!

Birli's uvfits implementation is based heavily on [Cotter](https://github.com/MWATelescope/cotter)'s, and as far as I can tell, Cotter didn't write this key, which is why we missed this.

I'd be happy to add this key in for you though. 

Have you got any suggestions on how we can validate that a UVFits file is AIPS 117 compliant? Maybe there's some tools that you use which are particularly strict about about uvfits metadata?

Side note: I've nearly finished implementing measurement set output in Birli (in the [ms](https://github.com/MWATelescope/Birli/tree/ms) branch), so if you're aware of a simple way of testing that these Birli-generated measurement sets are compatible with pyuvdata, do let me know!

Thanks

**Comment by derwentx** [comment]
Here are the other mandatory AIPS AN fields we're missing, do you have any insight into what values we might want to put in these keys? 

- `EXTVER` - Subarray number - `-1`? , `0`?
- `GSTIA0` - GST at 0h on reference date (degrees) - will have to figure out how to get this from PAL / ERFA
- `XYZHAND` - Handedness of station coordinates - I don't know whether this is `"LEFT"` or `"RIGHT"` in our case.
- `FRAME` - will be hard-coded as `"ITRF"`
- `NO_IF` - we don't use the IF table, so `-1`? , `0`?

The following are blank in Cotter, but let us know if these values are incorrect.

```
POLARX  =                   0.                                                  
POLARY  =                   0.                                                  
UT1UTC  =                   0.                                                  
DATUTC  =                   0.                                                                                                  
```

It's also worth noting that Birli-generated uvfits will have a different values from Cotter for some of these keys:

-  `FREQ` The Cotter-calculated value was slightly incorrect because of [this](https://github.com/MWATelescope/Birli/issues/6) 
- `TIMESYS` is called `TIMSYS` for some reason, is this an issue? should we write both?

**Comment by mkolopanis** [comment]
A lot of these aren't terribly well defined in the memo are they. I can tell you what we do in pyuvdata land. Maybe I can work out some of the context too and hopefully that can help?

- `EXTVER` we use 1 here. Presumably since we're only writing a single AIPS_AN version and someone assumed it was 1 indexed?
- `NO_IF` is the number of spectral windows. For mwax this is would probably be 1. 
- `POLARX`/`POLARY` 0 makes sense here I think. Unless there's an offset from North Pole in images.
- `UT1UTC` we also use 0 here.
- `DATUTC` would 0 if your `TIMESYS` is UTC. We assume UTC ourselves so it is always 0.
- `FREQ` :+1: 
- 'TIMESYS'/'TIMSYS' we look for both because CASA also writes TIMSYS. The memo does also state `TIMSYS` in the time system defintion so ¯\\\_(ツ)_/¯
- `GSTIA0` this one depends on your `RDATE` but I'm not 100% sure what sets the RDATE for our kind of data. We just use 0 to spoof this because we don't directly use it in any of our calculations.

@bhazelton  and @kartographer would be able to provide the most definitive answers. I think combined they wrote most of our UVFITS interface.

Regarding tools for compliance, I personally just make sure to have a field for every table entry in the memo. The strictest thing I know about metadata would probably be either the casa uvfits converter or pyuvdata itself. Being able to read the files in both of these is probably a "good enough" kind of metric since a lot of users I know use these as their data interfaces. That being said, I'm clearly biased :laughing:

**Comment by derwentx** [comment]
Awesome! Thanks for the answers. I should have something for you soon.

**Comment by cjordan** [comment]
Hey @mkolopanis, how is `NO_IF` used in pyuvdata (or other of your works)?  I believe this is mostly like 24; (in ideal conditions) we have 24 discrete "coarse bands"/"coarse channels" each containing 1/24th of the whole observations bandwidth, so I think these qualify as IFs.

**Comment by derwentx** [comment]
oops, didn't mean to close this! It's not quite done yet.

**Comment by mkolopanis** [comment]
So we handle `NO_IF` as the number of independent spectral windows. I can see how you could interpret each coarse band as its own spectral window. We just view the full band as a single window since it is contiguous with all coarse bands present.
The idea of multiple spectral windows I think is more common for things like the VLA when you observe in multiple bands that do not form a contiguous frequency band if concatenated.

**Comment by andreww5au** [comment]
For EOR observations, the 24 coarse channels are always contiguous, but there are other MWA users that want non-contiguous channels - two blocks of twelve channels, twelve blocks of two channels, etc. If you're implementing this header field now, you might as well do it properly by actually counting the number of non-contiguous channel blocks, rather than hard-coding in a value of 1.

**Comment by bhazelton** [comment]
Yes, we currently support non-contiguous MWA coarse bands in pyuvdata by labelling them as different spectral windows in our existing reader pre-MWAX files, and that will also be the case for MWAX files once that reader is merged in.

I have some more comments on some of these other uvfits keywords, I'll try to get them down in this issue tomorrow.

**Comment by bhazelton** [comment]
I believe that the existing MWA correlator fits file reader in pyuvdata does exactly what @andreww5au is suggesting.

**Comment by derwentx** [comment]
Hey folks, thanks for the comments.
I've written some tests to validate Birli matches our particular interpretation of AIPS 117, and once you're happy with these, I'll implement fixes. The fix to add the `FRAME` key has already been released. Please let me know if I've missed anything. https://github.com/MWATelescope/Birli/blob/4a56d448ea7cfa6d23115b2a0d0fe1a008de8aa0/src/io/uvfits.rs#L1837 

With the `NO_IF` keyword, I can add a ticket to implement spectral windows in uvfits the proper way, but i'm not aware of any software which reads the data like this, so if this is going to be implemented, I would need someone to volunteer as an owner for this feature, and validate that this works. it would also be quite some time before it can be prioritised on top of all the other high priority features, but it's still an option if someone wants it.

I found another vaguely worded keyword, OBS-DATE. Some programs include the time and use ISO8601 here, but others use YYYY-MM-DD, so I was wondering if anyone has any thoughts on which is correct. https://github.com/MWATelescope/Birli/issues/12

Thanks

**Comment by mkolopanis** [comment]
Regarding spectral windows, part of what bryna mentioned is that pyuvdata does handle the individual spectral windows properly (thanks to @kartographer).

**Comment by derwentx** [comment]
ah, sorry I didn't know what you meant by "church", and I worded my last comment poorly. What I meant by "implement spectral windows the proper way" was not just writing the number of groups of contiguous coarse channels / spectral windows into ANT->NO_IF, but also adding the IF axis to the UV table, and an FQ table filled with corresponding spectral window entries. Without the full implementation, I can't see the point of just putting that value in the NO_IF keyword, unless I'm misunderstanding the spec. From reading the source, it looks like pyuvdata does do this, so I'll open an issue
